version: '3'

services:
  node1:
    image: cassandra:latest
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=node1
      - CASSANDRA_NUM_TOKENS=128
    volumes:
      - node1_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  node2:
    image: cassandra:latest
    container_name: cassandra-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=node1
      - CASSANDRA_NUM_TOKENS=128
    volumes:
      - node2_data:/var/lib/cassandra
    depends_on:
      - node1

volumes:
  node1_data:
  node2_data:
